dimagi/couchdbkit

- couchdbkit/ext/django/forms.py
- couchdbkit/ext/django/loading.py
- setup.py
deprecation warnings on django 1.7 (Ignore branch name :) )
cc: @czue
> Deprecation warning

- couchdbkit/__init__.py
- couchdbkit/logging.py
- couchdbkit/resource.py
- couchdbkit/version.py
adds a logger to couchdbkit that records timing information
> add request logging

- couchdbkit/resource.py
> remove redundant assignment

- couchdbkit/client.py
- couchdbkit/logging.py
> log bulk save errors

- .travis.yml
- couchdbkit/ext/django/__init__.py
- couchdbkit/version.py
@dannyroberts cc: @calellowitz
> django 1.9 compatibility

- couchdbkit/ext/django/__init__.py
> django 1.7 fix

- couchdbkit/ext/django/__init__.py
- couchdbkit/ext/django/loading.py
- couchdbkit/ext/django/management/commands/sync_couchdb.py
- couchdbkit/ext/django/management/commands/sync_finish_couchdb.py
- couchdbkit/ext/django/management/commands/sync_prepare_couchdb.py
- couchdbkit/version.py
> drop support for django < 1.7

- couchdbkit/resource.py
- couchdbkit/version.py
@esoergel 
cross: https://github.com/dimagi/commcare-hq/pull/13542
> add more info to request logging

- couchdbkit/designer/fs.py
Only applies to `atomic` pushes.
Currently we push all design docs to couch regardless of whether or not there have been changes. This will allow us to only push (and index) design docs that have actually changed.
> don't push design docs if they haven't changed

- requirements_dev.txt
- tests/client_test.py
- tests/test_changes.py
- tests/test_consumer.py
- tests/test_loaders.py
- tests/test_resource.py
- tests/test_schema.py
> Removed unittest2.

- couchdbkit/version.py
- setup.py
- tests/test_schema.py
Seems like a good idea to test existing changes before adding more.
> bump to version 0.9.0.1

- couchdbkit/client.py
- couchdbkit/version.py
see https://api.travis-ci.org/v3/job/400913670/log.txt
>  raise ResourceNotFound in get_rev if document is not found

- couchdbkit/client.py
- couchdbkit/version.py
https://api.travis-ci.org/v3/job/401001484/log.txt
> make save_doc keep the same return values

- couchdbkit/client.py
- couchdbkit/version.py
Fixes https://api.travis-ci.org/v3/job/402199502/log.txt
> allow getting attachments with doc.get(doc_id, attachments=True)

- couchdbkit/client.py
This caused eCHIS deploy to fail:
```
[172.19.3.41] out: 2018-07-31 15:07:41,649 INFO Copy prepared design docs for 'app_manager' in couchdb
[172.19.3.41] out: Copying design docs for plugin app_manager
[172.19.3.41] out: Traceback (most recent call last):
[172.19.3.41] out:   File "manage.py", line 137, in <module>
[172.19.3.41] out:     execute_from_command_line(sys.argv)
[172.19.3.41] out:   File "/home/cchq/www/echis/releases/2018-07-31_14.13/python_env/local/lib/python2.7/site-packages/django/core/management/__init_.py", line 364, in execute_from_command_line
[172.19.3.41] out:     utility.execute()
[172.19.3.41] out:   File "/home/cchq/www/echis/releases/2018-07-31_14.13/python_env/local/lib/python2.7/site-packages/django/core/management/__init_.py", line 356, in execute …
```
> catch HTTPErrors

- couchdbkit/client.py
- couchdbkit/version.py
I feel ok doing this because:
1) HQ tests pass with these functions removed
2) I've given this code some time on staging, and no errors have happened yet.
> kill other functions

- couchdbkit/logging.py
- couchdbkit/version.py
- setup.py
- tests/test_logging.py
The request logger is not installed by default. It can be installed with `couchdbkit.logging.install_request_logger()`
@pr33thi @snopoke
> Add couchdb request logger

- couchdbkit/client.py
This will let us switch to keeping the username/password out of the URL
> Make server accept auth

- couchdbkit/client.py
- couchdbkit/logging.py
> Cleanup and support for db parameters

- couchdbkit/client.py
- couchdbkit/version.py
https://github.com/dimagi/couchdbkit/pull/66#pullrequestreview-175021984
@nickpell
> Fix urlparse import

- .travis.yml
- couchdbkit/client.py
- couchdbkit/version.py
- setup.py
This may reduce requests to couch considerably. Every time we query a view it results in two HTTP requests.
[was introduced when moving over to the cloudant lib](https://github.com/dimagi/couchdbkit/pull/55#pullrequestreview-142475890) . as I said there:
> I recognize that this is one of my own old commits, so I should have some more confidence and understanding of it, but I also think my old code is :hankey:  and confusing.
> Create view without fetching

- couchdbkit/ext/django/schema.py
Poked at this a while ago, but didn't make a PR at the time. Sending along now since @dannyroberts working on similar efforts.
> Django 2 compatibility
